nelmio_cors:
    defaults:
        # origin_regex: true
        # allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: [Origin, Content-Type, Accept, Authorization, Bearer]
        expose_headers: ['Link']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/[groups|users|login_check]': ~
           
